### ISSUE TITLE
guessLocale() return `en_US` which is not found

### ISSUE THREAD

**Issue by soimy** [yargs/yargs#1032]
Somehow in function `guessLocale`: `os-locale` module return `en_US` leads to missing `en_US.json`
I can only force locale to `en` in `require('yargs').locale('en')`

**Comment by bcoe** [comment]
an unrecognized locale should default to English, could you provide a stack trace?

**Comment by soimy** [comment]
Here is the stack trace:
```
Error: ENOENT: no such file or directory, stat '/Users/sym/Github/msdf-bmfont-xml/node_modules/yargs/locales/en_US.json'
    at Object.fs.statSync (fs.js:954:11)
    at Y18N._fileExistsSync (/Users/sym/Github/msdf-bmfont-xml/node_modules/y18n/index.js:99:15)
    at Y18N._resolveLocaleFile (/Users/sym/Github/msdf-bmfont-xml/node_modules/y18n/index.js:87:40)
    at Y18N._readLocaleFile (/Users/sym/Github/msdf-bmfont-xml/node_modules/y18n/index.js:69:27)
    at Y18N.__ (/Users/sym/Github/msdf-bmfont-xml/node_modules/y18n/index.js:26:38)
    at Object.self.getPositionalGroupName (/Users/sym/Github/msdf-bmfont-xml/node_modules/yargs/lib/usage.js:88:12)
    at Object.Yargs.self.positional (/Users/sym/Github/msdf-bmfont-xml/node_modules/yargs/yargs.js:699:27)
    at Object.require.usage [as builder] (/Users/sym/Github/msdf-bmfont-xml/cli.js:13:11)
    at Object.runCommand (/Users/sym/Github/msdf-bmfont-xml/node_modules/yargs/lib/command.js:182:35)
    at Object.parseArgs [as _parseArgs] (/Users/sym/Github/msdf-bmfont-xml/node_modules/yargs/yargs.js:1024:28)
```

**Comment by bcoe** [comment]
@soimy what version of Node.js are you using, I wonder if perhaps this logic doesn't work in newer Node versions?

https://github.com/yargs/y18n/blob/master/index.js#L94

**Comment by soimy** [comment]
I'm using latest LTS which is v8.9.3, also tested on v8.3.0 and v9.3.0

ENOENT reported on this line actually:
https://github.com/yargs/y18n/blob/master/index.js#L115

**Comment by soimy** [comment]
Turns out that I enabled break on all error in node-inspector debugger ... so the debugger stopped even the error was caught.
Closing this issue.
