### ISSUE TITLE
`yargs.parse(argv,callback)` issues call back before handler promise is finished.

### ISSUE THREAD

**Issue by E314c** [yargs/yargs#1069]
yargs v11.0.0

When using yargs.parse() with a callback, expected behaviour is for callback to be called after yargs parse has completed. It is also expected that command handlers accept promises in their returns.

Example code:
```javascript
const yargs = require('yargs');

yargs.command({
    command: 'test',
    description: 'a test command',
    handler: () => {
        return new Promise((resolve) => {
            setTimeout(() => {
                console.log('[Promise] finally executed');
                resolve('some result');
            }, 3000);
        });
    }
});

const callback = ()=>{
    console.log('[Yargs] Parse finished');
};

yargs.parse('test', (err, argv, output) => {
    callback(err, output);
});

console.log('[File] End');
```

outputs:
```
$ node index.js
[Yargs] Parse finished
[File] End
[Promise] finally executed 
```
expected:
```
[File] End
[Promise] finally executed 
[Yargs] Parse finished
```

Context: I'm using yargs inside REPL and need the callback to fire _after_ the command has finished processing, so REPL can continue correctly.

Possibly linked issues:
#510 : Adds in the Async handler support, but does not halt `parse` execution or pass promise back to user.
#918 : possibly a feature request for this?
#564 : Unanswered question on how to achieve this behaviour in yargs (though link provided to user space workaround/patch)

Workaround is discussed in #918 by attaching your promise to the argv and then checking it in the callback.

I would say that the callback in `yargs.parse` being called before command finishes could be seen as a bug, unless documentation is written to specify that it is expected behaviour and that async handlers will _not_ halt execution of `parse`'s callback.

**Comment by E314c** [comment]
Worth confirming that with the workaround idea from #918 works how I'd want it to:

```javascript
const yargs = require('yargs');

yargs.command({
    command: 'test',
    description: 'a test command',
    handler: (argv) => {
        argv.promisedResult = new Promise((resolve) => {
            setTimeout(() => {
                console.log('[Promise] finally executed');
                resolve('some result');
            }, 3000);
        });
        return argv.promisedResult;  //This line is actually redundant now. But it's how i'd prefer it to work.
    }
});

const callback = ()=>{
    console.log('[Yargs] Parse finished');
};

yargs.parse('test', (err, argv, output) => {
    console.log(argv);
    console.log(typeof argv.promisedResult);
    if(argv.promisedResult){
        argv.promisedResult.then(callback);
    } else {
        callback(err, output);
    }
});

console.log('[File] End');

```

But I feel like it's a tad cludgy to utilise side-effects of modifying `argv`  in order to achieve intended behaviour.

**Comment by zenflow** [comment]
I will see if I can fix this, since I introduced the issue with PR #1001

**Comment by E314c** [comment]
I wouldn't say introduced so much as it seems it was never built to handle it. 

Is there any intended usage for the return of a `handler` function? or is the return generally ignored?

For a "proper" fix, you may have to make a lot of stuff async and return the promise back up.
You could also circumnavigate it by attaching the result of the handler to the argvs and checking/waiting further down the line in the parse() function. There you could just wrap the handlerResult in a `Promise.all([handlerResult]).then(()=>{parserCallback();})`, which would handle promised and non-promised handler results.

**Comment by zenflow** [comment]
> Is there any intended usage for the return of a handler function? or is the return generally ignored?

Nope. The return value is completely ignored, unless it's a promise, in which case the resolution value is still completely ignored.

**Comment by SimonSchick** [comment]
@zenflow it would actually be really useful if the return value was passed into the `parse` callback.

**Comment by bcoe** [comment]
partial implementation here, would love more help:

https://github.com/nyamadori/yargs/pull/1

**Comment by SimonSchick** [comment]
I did something like that a while ago: 

```typescript
interface IHandlerExitOptions {
  exitProcess?: boolean;
}

/**
 * Unfortunately yargs does not allow global handling of command handler results.
 * This may be fixed this https://github.com/nyamadori/yargs/pull/1 in the future.
 * For now we hook into `require.extensions` and hook the individual command handlers
 * to achieve this global handling.
 * This hook also modifies all commands to exit by default unless an object with `exitProcess: false`
 * is resolved.
 */
function hookYargsHandlers() {
  const oldHandler = require.extensions['.js'];

  const binPath = resolve(__dirname, 'bin');
  require.extensions['.js'] = function(m: NodeModule, fileName: string) {
    const ret = oldHandler.call(this, m, fileName);
    if (fileName.startsWith(binPath)) {
      const command: yargs.CommandModule = m.exports.command;
      const handler = <(args: any) => Promise<void | IHandlerExitOptions> | void>command.handler;
      command.handler = async function(args: any) {
        const res = await handler.call(this, args);
        if (!res || res.exitProcess === undefined || res.exitProcess) {
          process.exit(0);
        }
        // Technically redundant because ignored but might not be in the future.
        return res;
      };
      m.exports = command;
    }
    return ret;
  };
}

hookYargsHandlers();
```

**Comment by bradfordlemley** [comment]
Another option to create an async command:
```
const yargs = require('yargs');
function myAsyncCmd(args){
  return new Promise((resolve, reject) => {
    const asyncifyCmd = cmd => ({
      ...cmd,
      handler: argv => resolve(cmd.handler(argv)),
    });
    yargs
      .command(asyncifyCmd(require('./commands/cmd1')))
      .command(asyncifyCmd(require('./commands/cmd2')))
      .demandCommand(1, 'No command given, see usage.')
      .help()
      .exitProcess(false)
      .parse(args, (err, argv, output) => {
        // cmd parse error, no command was invoked
        if (err) {
          console.error(output);
          reject(err);
        }
      });
  });
}
```

**Comment by givehug** [comment]
Noticed strange behavior when error is thrown in async handler.
```
require('yargs')
	.command({
		command: 'test',
		handler: async() => {
			console.log('LOG');
			throw new Error('ERROR');
		},
	})
	.parse(process.argv.slice(2));
```
output:
```
LOG
LOG
test.js test

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

ERROR
```
handler called twice.

Another thing is that options are displayed when async handler fails. When sync handler fails there is no options output.

**Comment by bcoe** [comment]
@E314c @zenflow would love some help digging into this at some point; we've continued to further improve promise handling, so it might be a good time to revisit this issue.

**Comment by marcbachmann** [comment]
I've successfully patched the existing module to properly support promises in the parse function.
Maybe we could do a pr for something like that as everything would still be completely synchronous up until the parse response handler.

```bash
$ node ./yargs-promise.js
Not enough non-option arguments: got 0, need at least 1

$ node ./yargs-promise.js failing
Error from command: Error: Some error correctly handled
    at Timeout.setTimeout [as _onTimeout] (/Users/marcbachmann/Development/yargs-promise/test.js:12:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

$ node ./yargs-promise.js successful
Some output from command: Some success correctly handled
```

<details>
  <summary>File: yargs-promise.js</summary>

```js
const yargs = require('yargs')
const {promisify} = require('util')

const cli = yargs
  .usage('Usage: $0 <command>')
  .demandCommand(1)
  .command({
    command: 'failing',
    description: 'Some failing command',
    async handler (args) {
     await new Promise((resolve, reject) => setTimeout(() => {
       reject(new Error('Some error correctly handled'))
     }, 1000))
    }
  })
  .command({
    command: 'successful',
    description: 'Some successful command',
    async handler (args) {
     return new Promise((resolve, reject) => setTimeout(() => {
       resolve('Some success correctly handled')
     }, 1000))
    }
  })
  .help()
  .alias('h', 'help')

patchCommandHandlers(cli)

const parse = (args) => {
  return new Promise((resolve, reject) => {
    cli.parse(args, {}, promiseExitHandler.bind(cli, resolve, reject))
  })
}

parse(process.argv.slice(2)).catch((err) => {
  if (err.name === 'YError') return console.error(err.message)
  console.error('Error from command:', err)
}).then((output) => {
  console.log('Some output from command:', output)
})


// Helpers are here
function patchCommandHandlers (yrgs) {
  const commands = yrgs.getCommandInstance().getCommandHandlers()
  for (const commandName of Object.keys(commands)) {
    const command = commands[commandName]
    patchCommandHandler(yrgs, command)
    patchCommandBuilder(yrgs, command)
  }
}

function patchCommandHandler (yrgs, command) {
  const originalHandler = command.___originalHandler || command.handler
  if (typeof originalHandler !== 'function') return

  command.___originalHandler = originalHandler
  command.handler = promisify((argv) => {
    argv.___promise = originalHandler(argv)
    return argv.___promise
  })
}

function patchCommandBuilder (yrgs, command) {
  const originalBuilder = command.___originalBuilder || command.builder
  if (typeof originalBuilder !== 'function') return

  command.___originalBuilder = originalBuilder
  command.builder = (argv) => {
    const val = originalBuilder(argv)
    patchCommandHandlers(yrgs)
    return val
  }
}

async function promiseExitHandler (resolve, reject, err, argv, output) {
  if (err && err.name === 'YError') {
    if (output) err.output = output
    return reject(err)
  }

  if (argv.___promise) {
    try {
      const result = (await argv.___promise) || output
      return resolve(result)
    } catch (err) {
      return reject(err)
    }
  }
}

async function defaultExitHandler (err, argv, output) {
  if (process.env.DEBUG) console.debug('exit handler', {err, argv, output}) // eslint-disable-line no-console, max-len
  if (output) process.stderr.write(`${output}\n`)
  if (err && err.name === 'YError') return process.exit(1)

  let _err
  if (argv.___promise) {
    try {
      await argv.___promise
    } catch (error) {
      _err = error
    }
  }

  if (process.env.DEBUG) console.debug('exit handler resolved', {err, argv, output}) // eslint-disable-line no-console, max-len
  if (_err) this.getUsageInstance().fail(null, _err)
}
```

</details>

**Comment by bcoe** [comment]
@marcbachmann @E314c it seems reasonable that `.parse()` would properly handle promises; I just want to make sure we think through all the ramifications appropriately, since we don't want yargs to gravitate way from working in sync mode -- feel free to open a patch so that I can look at your solution.

**Comment by tianyingchun** [comment]
any progress of this issue? or what's another choice for us if we wan't to know when the async handler has been finished?

**Comment by mleguen** [comment]
@tianyingchun Not much, I'm afraid. I hope I will have some time to be back on the "yargs async" file in the coming weeks.

**Comment by tianyingchun** [comment]
okay, i just wrap it using each command handler into new promise(), and emit `finished` event while any of command handler has been finished. it can fix my issue temporary maybe。 like:
```
  const cmdModule: YargsCommandModule<T, U> = {
    command,
    describe,
    builder,
    handler(args: YargsArguments<U>) {
      const factory = new commandFactory(args);
      return handlerQueue.add(factory.runHandle.bind(factory));
    },
  };
```
```
export const handlerQueue = {
  async add(handler: () => Promise<any>, name?: string) {
    const emitData = {
      handlerIndentifier: name,
    };
    let result;
    try {
      result = await handler();
      handlerEmitter.emit(ASYNC_CMD_HANDLER_FINISH, emitData);
    } catch (err) {
      handlerEmitter.emit(ASYNC_CMD_HANDLER_FINISH, emitData);
      throw err;
    }
    return result;
  },
};

```
  parse(argv: string[], callback?: YargsParseCallback<BaseArguments>) {
    const program = createCommander(this.options);
    this.commands.reduce((program, cmd) => program.command(cmd), program).parse(argv, this.options, callback);
    return this.wait<any>();
  }
  /**
   * Note:Only used to UT (jest)
   * using event emitter to hook the finished states of `async command handler`
   */
  private wait<T>() {
    return new Promise<T>((resolve) => {
      handlerEmitter.on(ASYNC_CMD_HANDLER_FINISH, () => {
        // console.debug(`async handler excuted`);
        resolve();
      });
    });
  }
```

**Comment by hongaar** [comment]
I use this pattern suggested in an earlier comment on this PR. In the command handler, set a custom property on the `argv` argument:

```ts
function handler (argv: Arguments<T>) {
  return argv.__promise = Promise.resolve(argv).then(async argv => {
    // do async things
  })
}
```
https://github.com/hongaar/bandersnatch/blob/alpha/src/command.ts#L216

Then in `yargs.parse`:

```ts
yargs.parse(argv, function parseCallback (err, argv: Arguments, output) {
  if (isPromise(argv.__promise)) {
    argv.__promise
      .then(function resolve(...args) {
        // Command handler resolved...
      })
      .catch(function reject(error) {
        // Command handler rejected...
      })
  } else {
    // Sync command handlers...
  }
})
```
https://github.com/hongaar/bandersnatch/blob/alpha/src/program.ts#L113

**Comment by fedecarg** [comment]
If you are here like me, you found through Google that the callback function doesn't work. 

If you only want to capture the output of your script, call your node script from another script and pipe the output:

```
const { execSync } = require('child_process');

try {
    const output = execSync(`./myscript.js --name Federico`,  { stdio: 'pipe' });
} catch (e) {
    console.log(e);
}
```

Good luck.

**Comment by joekiller** [comment]
I used a spy to capture the output and then tried to shape the call per the [.parse() docs](http://yargs.js.org/docs/#api-reference-parseargs-context-parsecallback).  Seems the trick is to await the parser and return that to the handler.

```
export async function execCmd(cmd: CommandModule, args: string): Promise<void> {
  const parser = yargs.command(cmd)
  return cmd.handler(await parser.parse(args));
}

const spyConsole = jest.spyOn(console, 'log').mockImplementation();
it('does a cmd test', async () => {
    beforeEach(() => spyConsole.mockReset());
    afterEach(() => spyConsole.mockReset());
    execCmd(myCmd, 'all my args')).
      .then(() => expect(spy.Console.mock.calls[0][0]).toContain('my cmd output'));
```

**Comment by bcoe** [comment]
@fedecarg  @joekiller in both your cases, are you using Promises for the handler?

We need to completely overhaul how yargs approaches async behavior, is what it comes down to. And it's not a small amount of work.

**Comment by joekiller** [comment]
@bcoe I figured it out. 

Yes these are promise handlers. Researching the progress thus far it appears I have to wrap everything such that the [finish hook `.onFinishCommand(async ...)`](https://github.com/yargs/yargs/blob/master/docs/advanced.md#command-finish-hook) closes over the async call.

Second try. If you wrap your command calls in the following `execCmd` promise, it'll always "do the work" prior to returning.

```
npm init -y
npm install jest typescript yargs ts-jest
```

jest.config.js
```
module.exports = {
	  transform: {'^.+\\.ts?$': 'ts-jest'},
	  testEnvironment: 'node',
	  testRegex: '.*\\.(test|spec)?\\.(ts|tsx)$',
	  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node']
};
```
Example test:

test.ts
```
import { Arguments, CommandModule } from 'yargs';
import * as yargs from 'yargs';
const spyConsole = jest.spyOn(console, 'log').mockImplementation();

const execCmd = async (cmd: CommandModule, args: string): Promise<void> => {
  return new Promise((resolve, reject) => {
    try {
      yargs
        .command(cmd)
        .onFinishCommand(async (r) => resolve(r))
        .exitProcess(false)
        .parse(args);
    } catch (e) {
      reject(e);
    }
  });
};

interface MooArgs extends Arguments {
  moo: string;
}

const mooCmd: CommandModule = {
  command: 'moo <moo>',
  describe: 'A cow goes',
  handler: async (argv: MooArgs) => {
    console.log('moo');
    console.log(argv.moo);
  },
};

it('will moo appropriately', async (done) => {
  return execCmd(mooCmd, 'moo meow')
    .then(() => expect(spyConsole.mock.calls[0][0]).toContain('moo'))
    .then(() => expect(spyConsole.mock.calls[1][0]).toContain('meow'))
    .then(() => done());
});
```


I assume it's best to wrap an entry point similarly:

```
#!/usr/bin/env node
import yargs = require('yargs');

const cmd = new Promise((resolve) => {
  yargs
    .commandDir('cmds')
    .onFinishCommand(async (r) => resolve(r)).argv;
});

export = dconCmd;
```

**Comment by tianyingchun** [comment]
I have removed my old patches, changed into `onFinishCommand` and  all unit test works fine. great job ~~ 💯

**Comment by bcoe** [comment]
@tianyingchun @joekiller just thinking out loud about the API surface, I wonder if we could make:

```js
await yargs.parseAsync()
```

and alias for"

```js
  return new Promise((resolve, reject) => {
    try {
      yargs
        .command(cmd)
        .onFinishCommand(async (r) => resolve(r))
        .exitProcess(false)
        .parse(args);
    } catch (e) {
      reject(e);
    }
  });
```

**Comment by tianyingchun** [comment]
yeah, i think. the parse mean we transform all parameters don't need to care the result to command exec,
if we provider `parseAsync()` maybe it will give me some `confusion`, what's is parse async?, i think onFinishCommand() is fine. cause of in most case we don't need to care when the command has been executed, maybe we need to case this  for `UNIT TEST` . so we can just wrap `onFInishedCommand` into Promise<> 
 
```
  public parse<T = TypeAny>(argv: string[], callback?: YargsParseCallback): Promise<T> {
    this.program = this.commands.reduce((program, cmd) => program.command(cmd), this.program);
    return new Promise((resolve) => {
      this.program
        .onFinishCommand((result) => {
          resolve(result);
        })
        .parse(argv, this.options, callback);
    });
  }
```
