### ISSUE TITLE
can't run example/usage-options.js

### ISSUE THREAD

**Issue by kenshinji** [yargs/yargs#1176]
After I issued `node usage-option.js`, it displays error message like below.

```
YError: Invalid second argument. Expected string or boolean but received object.
    at argumentTypeError (/Users/fred/git/stocks-cn/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/Users/fred/git/stocks-cn/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (<anonymous>)
    at argsert (/Users/fred/git/stocks-cn/node_modules/yargs/lib/argsert.js:42:21)
    at Object.Yargs.self.usage (/Users/fred/git/stocks-cn/node_modules/yargs/yargs.js:442:5)
    at Object.<anonymous> (/Users/fred/git/stocks-cn/usage-option.js:3:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

/Users/fred/git/stocks-cn/node_modules/yargs/yargs.js:450
        throw new YError('.usage() description must start with $0 if being used as alias for .command()')
        ^
YError: .usage() description must start with $0 if being used as alias for .command()
    at Object.Yargs.self.usage (/Users/fred/git/stocks-cn/node_modules/yargs/yargs.js:450:15)
    at Object.<anonymous> (/Users/fred/git/stocks-cn/usage-option.js:3:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I wonder whether the example code is deprecated.

**Comment by akhlesh** [comment]
Usage example is wrong as per given types. 2nd parameter shouldn't be an object.



```typescript
usage(message: string): Argv<T>;
usage<U>(command: string | ReadonlyArray<string>, description: string, builder?: (args: Argv<T>) => Argv<U>, handler?: (args: Arguments<U>) => void): Argv<T>;
usage<U>(command: string | ReadonlyArray<string>, showInHelp: boolean, builder?: (args: Argv<T>) => Argv<U>, handler?: (args: Arguments<U>) => void): Argv<T>;
usage<O extends { [key: string]: Options }>(command: string | ReadonlyArray<string>, description: string, builder?: O, handler?: (args: Arguments<InferredOptionTypes<O>>) => void): Argv<T>;
usage<O extends { [key: string]: Options }>(command: string | ReadonlyArray<string>, showInHelp: boolean, builder?: O, handler?: (args: Arguments<InferredOptionTypes<O>>) => void): Argv<T>;

**Comment by akhlesh** [comment]
try this
```typescript
var yargs = require('yargs');

var argv = yargs.usage('This is my awesome program').options({
  'about': {
    description: 'Provide some details about the author of this program',
    required: true,
    alias: 'a',
  },
  'info': {
    description: 'Provide some information about the node.js agains!!!!!!',
    boolean: true,
    alias: 'i'
  }
}).argv;

yargs.showHelp();

console.log('\n\nInspecting options');
console.dir(argv);
```

**Comment by bcoe** [comment]
@akhelesh thanks for the updated example.

Could I bother someone to submit an update to the docs, I will happily land a patch.
