### ISSUE TITLE
command handler called after validation failure (positional)

### ISSUE THREAD

**Issue by kyeotic** [yargs/yargs#1196]
Version: `12.0.1`

I have a command module that requires a single positional argument. I invoke it with no arguments, and its handler is still called. According to the [command docs](https://github.com/yargs/yargs/blob/master/docs/advanced.md#command-execution) failed validation should block the handler.

Here is the module

``` typescript
export function lotteryCommand(context: IAppContext): CommandModule {
  return {
    command: 'lottery <amount>',
    describe: 'Starts a lottery with the server.',
    builder: yargs =>
      yargs.positional('amount', {
        describe: 'amount of rep to bet. Cannot exceed your total rep.',
        type: 'number'
      }),
    handler: argv => {
      console.log('handling')
      argv.promisedResult = lotteryHandler(context, argv) // calls console.log('called')
      return argv.promisedResult
    }
  }
}
```

Here is the yargs loader

```typescript
yargs
    .scriptName(commandCharacter)
    .command(rollCommand())
    .command(promoteCommand(guild))
    .command(bgrCommand(context))
    .command(lotteryCommand(context))
    .demandCommand(1, 'Must provide at least one command')
    .recommendCommands()
    // .exitProcess(false)
    .help()
    .fail(async (help, error) => {
      console.log('failing', help, error)
      await channel.send(asMarkdown(help))
      if (error) {
        await notifyOwner(error, message)
      }
    })
    .parse(command as string[], { message }, async (err, argv, output) => {
      // Hack to get around parse not waiting for promises
      if (argv.promisedResult) {
        console.log('waiting', err)
        await argv.promisedResult.catch((e: Error) => {
          err = e
        })
      }
      console.log('finishing')
      if (err) return await notifyOwner(err, message)
      if (output) {
        await channel.send(asMarkdown(output))
      }
    })
```

and the console

The console outputs
```
failing Not enough non-option arguments: got 0, need at least 1 undefined
failing Missing required argument: amount undefined
handling
waiting null
called
finishing
```

**Comment by tyrsius** [comment]
For additional weirdness, calling `yargs.parse()` multiple times causes the failure handler to be called multiple times.

**Comment by hongaar** [comment]
Just bumping into this. Seems like a bug? Would be happy to contribute a PR, but quite new to this codebase. If someone could provide some pointers as to where to fix this, I'll see what I can do.

Example stack:

```
Error: Not enough non-option arguments: got 0, need at least 1
    at Program.failHandler (src\program.ts:120:36)
    at Object.fail (node_modules\yargs\lib\usage.js:41:17)
    at Object.positionalCount (node_modules\yargs\lib\validation.js:51:13)
    at populatePositionals (node_modules\yargs\lib\command.js:305:16)
    at Object.runCommand (node_modules\yargs\lib\command.js:218:23)
    at Object.parseArgs [as _parseArgs] (node_modules\yargs\yargs.js:1095:41)
    at Object.parse (node_modules\yargs\yargs.js:583:25)
    at src\program.ts:76:18
    at new Promise (<anonymous>)
    at Program.run (src\program.ts:75:12)
Executing with { args: { some: [] } }
```

**Comment by TemporalAgent7** [comment]
FWIW, I fixed this by calling `yargs.exit()` in fail(). Note that this won't actually terminate the process if you set `exitProcess(false)`, it just terminates the parse early and doesn't call the handler with erroneous inputs.

**Comment by Devorein** [comment]
Unfortunately, that's not working. I'm getting the error `yargs.exit is not a function` when calling `yargs.exit` inside the `fail` method.

**Comment by jly36963** [comment]
***Note:** I only know the most recent versions of the yargs API, so I apologize if you're locked into older versions and my advice isn't relevant.*

My observations:

- The handler can be async. This removes the need for using the parse callback to await the result. 
- The current docs warn that the parse callback has the side effect of setting exitProcess to false, which means that failed validation will not stop the handler from running.
  - [docs](https://yargs.js.org/docs/#api-reference-parseargs-context-parsecallback)
  - [related issue](https://github.com/yargs/yargs/issues/1975)

The following code works with yargs@17:

- If the expected positional is provided, the handler runs as expected. 
- If it isn't provided, the handler is not run and the help output is shown

```js
yargs
  .command({
    command: "cmd <pos>",
    desc: "cmd desc",
    builder: (yargs) =>
      yargs.positional("pos", {
        desc: "pos desc",
        type: "number",
      }),
    handler: async (argv) => {
      console.log("handling");
      const result = await doSomething(argv);
      console.log({ result });
      return result;
    },
  })
  .help()
  .parse('cmd 1');

async function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function doSomething(argv) {
  await sleep(1000);
  return argv;
}
```

logs when positional is provided:

```
handling
{
  result: {
    _: [ 'cmd' ],
    '$0': 'test-issue.js',
    pos: 1
  }
}
```

logs when positional is not provided:

```
Positionals:
  pos  pos desc                                              [number] [required]

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```
