### ISSUE TITLE
Update dependencies for Node 11

### ISSUE THREAD

**Issue by aduh95** [yargs/yargs#1200]
When I use `yargs` with the nightly version of Node.js, I got the following error:

```bash
$ node --version
v11.0.0-nightly20180810346f2a7bec
$ node -p "require('yargs').argv"
execa/lib/errname: unable to establish process.binding('uv') Error: No such module: uv
    at process.binding (internal/bootstrap/loaders.js:81:36)
    at Object.<anonymous> (.../node_modules/execa/lib/errname.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../node_modules/execa/index.js:11:17)
{ _: [], '$0': '' }
```

The problem has been fixed by https://github.com/sindresorhus/execa/pull/125, and I think upgrading `os-locale` dependency to v3 should solve this.

FYI Node.js 11 is expected to be released on 2018-10-23 [[source]](https://github.com/nodejs/Release#release-schedule).

**Comment by aduh95** [comment]
Fixed in `v12.0.2`
