### ISSUE TITLE
Error: Cannot find module './lib/middleware'

### ISSUE THREAD

**Issue by vamshi9666** [yargs/yargs#1205]
i tried to use _webpack_ and after seeing i realized , its something with yargs. 
in yargs.js 
`./lib/middleware.js` is imported 
and there is no` middleware.js` in `lib/`

**Log is as in image below** 
`
Error: Cannot find module './lib/middleware'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/home/vamshi/my-appps/react/vamshi9666.github.io/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/vamshi/my-appps/react/vamshi9666.github.io/node_modules/yargs/yargs.js:14:27)
    at Module._compile (/home/vamshi/my-appps/react/vamshi9666.github.io/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vamshi9666.github.io@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vamshi9666.github.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by aorinevo** [comment]
Hi @vamshi9666,

I'm not sure what the issue is but the file is definitely there: https://github.com/yargs/yargs/blob/master/lib/middleware.js

Might be an issue with you you're bundling yargs with webpack.
