### ISSUE TITLE
Command failed. message: yargs error?

### ISSUE THREAD

**Issue by DrunkenPoney** [yargs/yargs#1253]
I've built a command line with yargs and I wanted to try it to see if it works but I got this message: `yargs error`.

So i've added a fail callback so I can see the stacktrace but it wasn'T helpful at all since I still can't see where's the problem coming from.<br>
Here is the stacktrace:
```stacktrace
YError: yargs error
    at Object.parseArgs [as _parseArgs] (/home/drunkenponey/projects/progres/TP4/api/data/node_modules/yargs/yargs.js:1138:33)
    at Object.get [as argv] (/home/drunkenponey/projects/progres/TP4/api/data/node_modules/yargs/yargs.js:1004:21)
    at Object.<anonymous> (/home/drunkenponey/projects/progres/TP4/api/data/cli.js:4:49)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
```

It's seems to crash when I call/use argv which seems to be a getter.

So nothing of this helps me to find out what's wrong cause seriously `yargs error` does not tell me much.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
