### ISSUE TITLE
SyntaxError: Identifier 'encoding' has already been declared

### ISSUE THREAD

**Issue by jacobgasser** [yargs/yargs#1398]
`C:\Users\Jacob\Desktop\TransREACH\node_modules\yargs\yargs.js:1163
      else throw err
           ^

SyntaxError: Identifier 'encoding' has already been declared
    at Object.require.demand.command.opts [as handler] (C:\Users\Jacob\Desktop\T
ransREACH\testa.js:244:7)
    at Object.runCommand (C:\Users\Jacob\Desktop\TransREACH\node_modules\yargs\l
ib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Users\Jacob\Desktop\TransREACH\node_
modules\yargs\yargs.js:1078:30)
    at Object.get [as argv] (C:\Users\Jacob\Desktop\TransREACH\node_modules\yarg
s\yargs.js:1012:21)
    at Object.<anonymous> (C:\Users\Jacob\Desktop\TransREACH\testa.js:286:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
`

I get this error when I try to run a program, I don't think it is on my end since it originates from the library, but I could be wrong. I believe it is version 13.0.0

**Comment by mleguen** [comment]
Could you please give us some more details about how you use yargs, to.be able to reproduce the issue?

Although the exception looks like it is thrown by the library in the stack trace, it may be thrown in one of the handlers you passed to yargs.

**Comment by mleguen** [comment]
@jacobgasser Looking more closely at the stack trace, it says you are redefining `encoding` in the handler you pass to `command()` on line 244 of your `testa.js` file.

So, it looks like it is not related to yargs.
