### ISSUE TITLE
Error with commandDir: ENOENT

### ISSUE THREAD

**Issue by qwang07** [yargs/yargs#1693]
ENVIRONMENT:
yargs: 15.4.1
node: v14.5.0

Here is my project structure:
```
Project
  |_subcmd
     |_init.js
     |_create.js
  |_main.js
```
In `main.js`:
```
#!/usr/bin/env node
import yargs from 'yargs'
import { createRequire } from 'module'
const version = createRequire(import.meta.url)('./package.json').version

yargs
  .usage('Usage: flow [--help] [--version] <command> [args]')
  .commandDir('subcmd')
  .help()
  .version(version)
  .demandCommand(1, "\nPlease follow the instruction.")
  .fail((msg, err, yargs) => {
    errMessage = msg || err.message
    console.error(yargs.help())
    console.error(errMessage)
    process.exit(1)
  })
  .argv
```
when I using the command, it always show Error of ENOENT:
```
Error: ENOENT: no such file or directory, scandir '/Users/qwang/file:/Users/qwang/Documents/Cmd/javascript/Project/subcmd'
    at Object.readdirSync (fs.js:981:3)
    at requireDirectory (/Users/qwang/Documents/Apps/javascript/flow/node_modules/require-directory/index.js:59:6)
    at Object.addDirectory (/Users/qwang/Documents/Apps/javascript/flow/node_modules/yargs/build/lib/command.js:110:9)
    at Object.Yargs.self.commandDir (/Users/qwang/Documents/Apps/javascript/flow/node_modules/yargs/build/lib/yargs.js:379:17)
    at file:///Users/qwang/Documents/Apps/javascript/flow/main.js:8:4
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:162:24) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/qwang/file:/Users/qwang/Documents/Cmd/javascript/Project/subcmd'
}
```
`/Users/qwang` is where I running the command, it will change if I running the command somewhere else.

**Comment by AntoninRousset** [comment]
Same issue with
yargs: 17.7.2
node: v20.2.0

**Comment by AntoninRousset** [comment]
I got this issue while using ESM, see the [docs](https://github.com/yargs/yargs/blob/main/docs/advanced.md#example-command-hierarchy-using-indexmjs).

**Comment by armordog** [comment]
Does this mean you can't use `commandDir` with esm?

**Comment by shadowspawn** [comment]
> _Note: `commandDir()` does not work with ESM or Deno, see [hierarchy using index.mjs](https://github.com/yargs/yargs/blob/main/docs/advanced.md#esm-hierarchy) for an example of building a complex nested CLI using ESM._

https://github.com/yargs/yargs/blob/main/docs/advanced.md#commanddirdirectory-opts

**Comment by shadowspawn** [comment]
Support for `commandDir` in ESM files was added in Yargs 18.

**Comment by xenoterracide** [comment]
AI seems to think I hit this issue with git-conventional-commits, yarn pnp and node 24, so +1 ;)

**Comment by shadowspawn** [comment]
Closing this as stale. esm support for `commandDir` shipped in Yargs 18.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
