### ISSUE TITLE
Cannot find module 'cliui' from '../node_modules/yargs/build/lib/usage.js'

### ISSUE THREAD

**Issue by dillonredding** [yargs/yargs#1700]
There seems to be a problem when testing a command module (as recommended [here](https://github.com/yargs/yargs/blob/master/docs/advanced.md#testing-a-command-module)) while using the [`mock-fs` library](https://www.npmjs.com/package/mock-fs) (v4.12.0).

To recreate the issue, here is the bare minimum command module `foo.ts` (using `yargs` v15.4.1):

```ts
import { Arguments } from 'yargs';

export const command = 'foo';

export function handler(args: Arguments): void {
    // do stuff...
}
```

(You don't have to use `fs` to trigger the error.)

Then in `foo.test.ts` (using `jest` v26.1.0):

```ts
import yargs, { Argv } from 'yargs';
import mockFs from 'mock-fs';

afterEach(() => {
    mockFs.restore();
});

describe('foo command', () => {
    const parser = yargs.command(require('./foo')).help();

    it('should be helpful', async () => {
        mockFs({});

        const output = await new Promise(resolve => {
            parser.parse('foo --help', (error: Error, argv: Argv, output: string) => {
                resolve(output);
            });
        });

        expect(output).toContain('Show help');
    });
});
```

After running this test I get:

```
 FAIL  src/foo.test.ts
  ● test command › should resolve JSON references in OpenAPI document

    Cannot find module 'cliui' from '../node_modules/yargs/build/lib/usage.js'

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:308:11)
      at Object.help (../node_modules/yargs/build/lib/usage.js:167:20)
      at Object.self.showHelp (../node_modules/yargs/build/lib/usage.js:435:19)
      at Object.Yargs.self.showHelp (../node_modules/yargs/build/lib/yargs.js:790:15)
      at ../node_modules/yargs/build/lib/yargs.js:1100:30
```

If I leave out the call to `mockFs`, the test passes. Any suggestions?

**Comment by bcoe** [comment]
@dillonredding were you able to find a workaround for this?

**Comment by dillonredding** [comment]
@bcoe, no, I was unable to find the source of the issue.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
