### ISSUE TITLE
npm breaks on yargs install

### ISSUE THREAD

**Issue by prographo** [yargs/yargs#1764]
```
$ npm i yargs
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "yargs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

```

**Comment by bcoe** [comment]
Hey @prographo, that looks like a fairly old version of Node.js you're running. 8.x reached end of life a year ago I believe. Could you upgrade to a supported version of Node.js, and try?

**Comment by bcoe** [comment]
@prographo closing this since I didn't hear a response, @prographo let me know if you still need any help.
