### ISSUE TITLE
Example (string.js) error "Too many arguments provided. Expected max 1 but received 2."

### ISSUE THREAD

**Issue by DasdWaller** [yargs/yargs#1809]
OS: Windows 10 (latest)
Node: 14.15.1
NPM: 6.14.8
Use: NVM  for Windows (NVM4W) and Windows Terminal

1. I create a `project-cli` file on bin directory
2. Install the `16.1.1`version of `yargs` package
3. The code on `project-cli`:
```
#!/usr/bin/env node

const yargs = require('yargs/yargs');
// const { hideBin } = require('yargs/helpers');

var argv = yargs(process.argv.slice(2))
    .string('x', 'y')
    .argv;

console.log([ argv.x, argv.y ]);
```
4. I set `bin` and values on `package.json`
5. I run `npm link`
6. I run on windows terminal:
`project-cli -x 000123 -y 9876`

Show error:
```
YError: Too many arguments provided. Expected max 1 but received 2.
    at argsert (path_to_my_project\project-cli\node_modules\yargs\build\index.cjs:128:19)
    at Object.Yargs.self.string (path_to_my_project\project-cli\node_modules\yargs\build\index.cjs:1917:9)
    at Object.<anonymous> (path_to_my_project\project-cli\bin\cli:7:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[ '000123', 9876 ]

```

**Comment by bcoe** [comment]
[.string()](https://github.com/yargs/yargs/blob/master/docs/api.md#stringkey) accepts a single argument, which is a single option you'd like to have interpreted as a `string`.

If you'd like to configure more than one at a time, you can pass `.string(['x', 'y'])`.
