### ISSUE TITLE
Getting typeerror yargs.[methodname] is not a function using ES6 + node.js + yargs

### ISSUE THREAD

**Issue by ctcoleman** [yargs/yargs#1854]
So, I'm doing a nodejs tutorial, but the tutorial isn't updated to ES6 and I just wanted to update the code as I go along. I get the program to run just fine using require('yargs'), but keep getting yargs.command, yargs.argv, etc. is not a function. This happens with any and all yargs methods. I receive the error whether I try to use it in this example or any other. It's my understanding that nodejs now supports import/export statements, as does yargs so I'm not using a bundler at all (I'm under the impression with ES6 supported in node and yargs I don't need a bundler). I have set my app as "type: module" and also tried saving my app.js as an .mjs file.  Listed below is the working vs. non-working(ES6) with terminal output. If it is a developer error I apologize for posting this as an issue, but please let me know...

Working code...

```
// ipmort module libraries from node package manager
const yargs = require('yargs')
const notes = require('./notes.js')

// Output colors
const chalk = require('chalk')
let jenkinsColor = '#bd93f9'
let successColor = '#50fa7b'
let failureColor = '#ff5555'

// Yargs stored version number
yargs.version('1.0.0')

// --- ADD COMMAND ----
yargs.command({
  command: 'add',
  describe: 'Have Jenkins add a new note',
  builder: {
    title: {
      describe: 'Note title',
      demandOption: true,
      type: 'string'
    },
    body: {
      describe: 'Note content',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.addNote(argv.title, argv.body)
  }
})

// --- REMOVE COMMAND ----
yargs.command({
  command: 'remove',
  describe: 'Have Jenkins remove an existing note',
  builder: {
    title: {
      describe: 'Note to be deleted',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.removeNote(argv.title)
  } 
})

// --- READ COMMAND ----
yargs.command({
  command: 'read',
  describe: 'Have Jenkins read your notes',
  handler() {
    console.log('Reading your notes, sir...')
  }
})

// --- LIST COMMAND ----
yargs.command({
  command: 'list',
  describe: 'Have Jenkins list your notes',
  handler() {
   console.log('Removing your note, sir...')
  }
})

yargs.parse()
```

Terminal output...

```
node-notes-app$ node app.js add --title="Test Title" --body="testing testing 123"

      ...............................
      + Test Title
      ...............................
      + + testing testing 123
    
SUCCESS
Adding your new note to your list, sir...
christopher@rra-debian-desktop:~/Documents/IBM/FED/NodeJS/node-notes-app$ 
```

ES6 - Not working

```
// import module libraries from node package manager
import yargs from 'yargs'
// import notes from './notes.js'

// Yargs stored version number
yargs.version('1.0.0')

// --- ADD COMMAND ----
yargs.command({
  command: 'add',
  describe: 'Have Jenkins add a new note',
  builder: {
    title: {
      describe: 'Note title',
      demandOption: true,
      type: 'string'
    },
    body: {
      describe: 'Note content',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.addNote(argv.title, argv.body)
  }
})

// --- REMOVE COMMAND ----
yargs.command({
  command: 'remove',
  describe: 'Have Jenkins remove an existing note',
  builder: {
    title: {
      describe: 'Note to be deleted',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.removeNote(argv.title)
  } 
})

// --- READ COMMAND ----
yargs.command({
  command: 'read',
  describe: 'Have Jenkins read your notes',
  handler() {
    console.log('Reading your notes, sir...')
  }
})

// --- LIST COMMAND ----
yargs.command({
  command: 'list',
  describe: 'Have Jenkins list your notes',
  handler() {
   console.log('Removing your note, sir...')
  }
})

yargs.parse()
```

ES6 Terminal output...

```
app.mjs:12
yargs.version('1.0.0')
      ^

TypeError: yargs.version is not a function
    at file:///home/christopher/Documents/IBM/FED/NodeJS/node-notes-app/app.mjs:12:7
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by davidfilat** [comment]
Same here!

**Comment by SimoneGianniHNP** [comment]
Actually, it's badly broken. I've been using the following example from yargs examples here: 
https://github.com/yargs/yargs/blob/master/docs/examples.md#yargs-is-here-to-help-you

Except i replaced require with import:

```
import yargs  from "yargs";

var argv = yargs(process.argv.slice(2))
    .usage('Usage: $0 <command> [options]')
    .command('count', 'Count the lines in a file')
    .example('$0 count -f foo.js', 'count the lines in the given file')
    .alias('f', 'file')
    .nargs('f', 1)
    .describe('f', 'Load a file')
    .demandOption(['f'])
    .help('h')
    .alias('h', 'help')
    .epilog('copyright 2019')
    .argv;

console.log("Args are", argv);
```

It behaves strange:

```
Main.js count -f something

Args are {
  _: [ 'count' ],
  f: 'something',
  '-f': 'something',
  count: undefined,
  something: undefined,
  '$0': 'Main.js'
}
```

Notice that -f has not been normalized to both "f" and "file", as it should be.

```
Main.js count --file something
Main.js count

Count the lines in a file

Options:
      --version    Show version number                                 [boolean]
  -f, --file       Load a file                                        [required]
  -h, --help       Show help                                           [boolean]
      --count
      ----file
      --something

Missing required argument: f
```

Notice that it did not recognize --file as an alias of -s, and instead it considers a ----file and a --something options that just don't exist.

```
Main.js count --file=something
Args are {
  _: [ 'count' ],
  file: 'something',
  f: 'something',
  count: undefined,
  '--file=something': undefined,
  'file=something': undefined,
  '$0': 'Main.js'
}
```

With --file=something it works more or less as expected!

```
Main.js count -f=something
Args are {
  _: [ 'count' ],
  f: 'something',
  file: 'something',
  count: undefined,
  '-f=something': undefined,
  'f=something': undefined,
  '$0': 'Main.js'
}
```

Also with -f=something, which is a weird syntax.

```
Main.js -h
Usage: Main.js <command> [options]

Commands:
  Main.js count  Count the lines in a file

Options:
      --version  Show version number                                   [boolean]
  -f, --file     Load a file                                          [required]
      ---h

Examples:
  Main.js count -f foo.js  count the lines in the given file

copyright 2019
```

Notice the ---h phantom option.


Everything works correctly replacing:

```
import yargs  from "yargs";
```

with old skool

```
const yargs = require('yargs/yargs');
```

Watching the transpiled sources, the import is translated to:

```
const yargs_1 = require("yargs");
var argv = yargs_1.default(process.argv.slice(2))
```

While the require is transpiled to:

```
const yargs = require('yargs/yargs');
var argv = yargs(process.argv.slice(2))
```

So, I think "yargs".default is a broken kinda working version of "yargs/yargs".

Tested down to version 15, same issue.

I don't manage to debug all the .mjs .cjs helpers and shims to understand what is broken here, hope some dev can help.

**Comment by bcoe** [comment]
@davidfilat @ctcoleman in ES6, yargs is no longer a singleton, so you need to call `yargs()` to get an instance of yargs, at which point the API is identical, here's a simple example:

```js
import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'

yargs(hideBin(process.argv))
  .command('curl <url>', 'fetch the contents of the URL', () => {}, (argv) => {
    console.info(argv)
  })
  .demandCommand(1)
  .argv
```

Here's your example rewritten:

```js
// import module libraries from node package manager
import yargs from 'yargs'
// import notes from './notes.js'

// Yargs stored version number
const y = yargs()
y.version('1.0.0')

// --- ADD COMMAND ----
y.command({
  command: 'add',
  describe: 'Have Jenkins add a new note',
  builder: {
    title: {
      describe: 'Note title',
      demandOption: true,
      type: 'string'
    },
    body: {
      describe: 'Note content',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.addNote(argv.title, argv.body)
  }
})

// --- REMOVE COMMAND ----
y.command({
  command: 'remove',
  describe: 'Have Jenkins remove an existing note',
  builder: {
    title: {
      describe: 'Note to be deleted',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.removeNote(argv.title)
  } 
})

// --- READ COMMAND ----
y.command({
  command: 'read',
  describe: 'Have Jenkins read your notes',
  handler() {
    console.log('Reading your notes, sir...')
  }
})

// --- LIST COMMAND ----
y.command({
  command: 'list',
  describe: 'Have Jenkins list your notes',
  handler() {
   console.log('Removing your note, sir...')
  }
})

y.parse(process.argv.slice(2))
```

----


@SimoneGianniHNP I don't have a clue what's happening to you, and can't reproduce locally. Could you create an example repository that demonstrates this behavior? (I think it might actually be an issue with your local configuration).

**Comment by davidfilat** [comment]
Thank you @bcoe! I found the same example in the Github repo README! But your comment will relieve a lot of headache for a lot of people! :D

**Comment by SimoneGianniHNP** [comment]
@bcoe before setting up the project, maybe one word can point you in the right direction: TypeScript :D

**Comment by ctcoleman** [comment]
Thanks @bcoe. I see exactly what you mean. I really appreciate the feedback. @SimoneGianniHNP actually that's right where I'm headed next is learning Typescript. It feels like staying a step ahead of the JS game with Typescript. Typescript seems to be picking up a lot of hype.

**Comment by ctcoleman** [comment]
Worked like a charm...

Working reformatted code...

```
import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'
import notes from './notes.mjs'

const yarg = yargs(hideBin(process.argv))

// Yargs stored version number
yarg.version('1.0.0')

// --- ADD COMMAND ----
yarg.command({
  command: 'add',
  describe: 'Have Jenkins add a new note',
  builder: {
    title: {
      describe: 'Note title',
      demandOption: true,
      type: 'string'
    },
    body: {
      describe: 'Note content',
      demandOption: true,
      type: 'string'
    }
  },
  handler(argv) {
    notes.addNote(argv.title, argv.body)
  }
})
```

Terminal output..
```
~/Projects/IBM/BED/NodeJS/node-notes-app$ node app.mjs --help
app.mjs [command]

Commands:
  app.mjs add     Have Jenkins add a new note
  app.mjs remove  Have Jenkins remove an existing note
  app.mjs read    Have Jenkins read your notes
  app.mjs list    Have Jenkins list your notes

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

Thanks again@bcoe
