### ISSUE TITLE
 Package exports for 'node_modules/yargs' do not define a valid './helpers' target

### ISSUE THREAD

**Issue by fxck** [yargs/yargs#1884]
Getting this error, node v13.2.0, "yargs": "^16.2.0",

used the simple example

```
#!/usr/bin/env node
const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers')
const argv = yargs(hideBin(process.argv)).argv

if (argv.ships > 3 && argv.distance < 53.5) {
  console.log('Plunder more riffiwobbles!')
} else {
  console.log('Retreat from the xupptumblers!')
}
```

```
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: Package exports for '/Users/fxck/www/zerops/node_modules/yargs' do not define a valid './helpers' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:607:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/Users/fxck/www/zerops/tools/env-replace.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by fxck** [comment]
works fine with v14.15.4, is yargs not compatible with older versions of node?

```  
"engines": {
  "node": ">=10"
}
```

given this I would assume it should be working with anything above 10..

**Comment by fxck** [comment]
hm.. works with v12.21.0 as well, so it has something to do with 13 particularly..

**Comment by bcoe** [comment]
@fxck it seems to work fine in anything over `13.7.0`, are you able to upgrade the version of `13` you're using in your environment?

Since I believe v13 is EOL, I don't know that this is worth fixing (if the bug has been addressed on the latest releases of 13).

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
