### ISSUE TITLE
ts-jest says `The requested module 'yargs/helpers' does not provide an export named 'hideBin'`

### ISSUE THREAD

**Issue by junseinagao** [yargs/yargs#2068]
Hi, I have a question.

I'm going to use yargs in the project have ts-jest.

ts-jest said `The requested module 'yargs/helpers' does not provide an export named 'hideBin'` but I know `yargs/helper` have export function `hideBin`

🐚 log
```bash
yarn run v1.22.17
$ node --experimental-vm-modules node_modules/jest/bin/jest.js
(node:22533) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  src/main.spec.ts
  ● Test suite failed to run

    SyntaxError: The requested module 'yargs/helpers' does not provide an export named 'hideBin'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:779:5)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:401:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.485 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This script that imported in main.spec.ts invoked this error.

setup.ts
```ts
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import path from "path";
import dotenv from "dotenv";
const __dirname = path.dirname(new URL(import.meta.url).pathname);

dotenv.config({ path: path.resolve(__dirname, "../.env") });
const args = yargs(hideBin(process.argv)).parse();

export default args;
```

I solved this problem not importing hideBin.

setup.ts (resolved problem)
```ts
import yargs from "yargs";
import path from "path";
import dotenv from "dotenv";
const __dirname = path.dirname(new URL(import.meta.url).pathname);

dotenv.config({ path: path.resolve(__dirname, "../.env") });
const args = yargs(process.argv.slice(2)).parse();

export default args;
```

It's mysterious. Someone knows why this problem happen?

I'm using this `jest.config.js`

```js
module.exports = {
  // [...]
  preset: "ts-jest/presets/default-esm", // or other ESM presets
  globals: {
    "ts-jest": {
      useESM: true,
    },
  },
  moduleNameMapper: {
    "^(\\.{1,2}/.*)\\.js$": "$1",
  },
};
```

**Comment by AndyClausen** [comment]
I get the same message but for `argv` when using yargs in an esm project.
Maybe this needs its own issue, but I thought it could be related.

Importing like this makes it fail with `The requested module 'yargs' does not provide an export named 'argv'`:
```ts
import { argv } from "yargs";
```

Importing like this makes `yargs` a function and `yargs.argv` undefined:
```ts
import yargs from "yargs";
const { argv } = yargs;
console.log(argv._[0]); // Cannot read properties of undefined (reading '_')
```

Importing like before, but with running yargs as a function first works:
```ts
import yargs from "yargs";
const { argv } = yargs(process.argv);
console.log(argv._[0]); // works!
```

This only became a problem when I switched to esm.

**Comment by bcoe** [comment]
@AndyClausen I believe the ESM version of yargs drops the *magic* `.argv` accessor, try the following:

```
import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'

yargs(hideBin(process.argv))
  .command('curl <url>', 'fetch the contents of the URL', () => {}, (argv) => {
    console.info(argv)
  })
  .demandCommand(1)
  .parse()
```

`.parse()` is equivalent to `.argv` but less magic.

**Comment by praveendvd** [comment]
> @AndyClausen I believe the ESM version of yargs drops the _magic_ `.argv` accessor, try the following:
> 
> ```
> import yargs from 'yargs'
> import { hideBin } from 'yargs/helpers'
> 
> yargs(hideBin(process.argv))
>   .command('curl <url>', 'fetch the contents of the URL', () => {}, (argv) => {
>     console.info(argv)
>   })
>   .demandCommand(1)
>   .parse()
> ```
> 
> `.parse()` is equivalent to `.argv` but less magic.

@bcoe  this works with normal package , but with jest test it throws the error mentioned in this bug . Is there any work around for this ?

**Comment by bcoe** [comment]
@praveendvd could you open an issue on `ts-jest` as well, perhaps they have some direction? This seems like a bug with how they're handling ESM vs., CJS requires.

**Comment by praveendvd** [comment]
> @praveendvd could you open an issue on `ts-jest` as well, perhaps they have some direction? This seems like a bug with how they're handling ESM vs., CJS requires.

https://github.com/facebook/jest/issues/12284 

Already did it thank you
