### ISSUE TITLE
loading a directory of commands is not supported yet for ESM

### ISSUE THREAD

**Issue by gee4vee** [yargs/yargs#2152]
What should we do with this error?

```
~/g/D/blueprint4ts [main]{7} ⛈️ »  yarn hello greet gabe                                                              {10:59:23}
yarn run v1.22.17
$ ./dist/cli.js greet gabe
file:///Users/gvalenc/git/DevX/testmodule/node_modules/yargs/lib/platform-shims/esm.mjs:38
    throw new YError(REQUIRE_DIRECTORY_ERROR)
          ^

YError: loading a directory of commands is not supported yet for ESM
    at Object.getCallerFile (file:///Users/gvalenc/git/DevX/testmodule/node_modules/yargs/lib/platform-shims/esm.mjs:38:11)
    at YargsInstance.commandDir (file:///Users/gvalenc/git/DevX/testmodule/node_modules/yargs/build/lib/yargs-factory.js:285:145)
    at file:///Users/gvalenc/git/DevX/testmodule/dist/cli.js:6:4
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
error Command failed with exit code 1.
```

package.json
```
{
  "name": "testmodule",
  "version": "0.0.1",
  "description": "test",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "/dist"
  ],
  "type": "module",
  "scripts": {
    "clean": "rimraf dist",
    "build": "yarn clean && tsc && npx prettier --write ./dist && chmod +x ./dist/cli.js",
    "test": "jest",
    "test:watch": "jest --watch",
    "lint": "npx eslint ./",
    "lint:watch": "npx esw --ext .js,.ts ./src --watch",
    "hello": "./dist/cli.js"
  },
  "keywords": [],
  "author": "",
  "license": "Apache-2.0",
  "devDependencies": {
    "@babel/core": "^7.17.8",
    "@types/jest": "^27.4.1",
    "@typescript-eslint/eslint-plugin": "^5.16.0",
    "@typescript-eslint/parser": "^5.16.0",
    "babel-loader": "^8.2.3",
    "babel-preset-env": "^1.7.0",
    "eslint": "^8.11.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-watch": "^8.0.0",
    "jest": "^27.5.1",
    "prettier": "2.6.0",
    "prettier-plugin-multiline-arrays": "^0.0.4",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.1.3",
    "typescript": "^4.6.2"
  },
  "dependencies": {
    "@types/yargs": "^17.0.10",
    "import": "^0.0.6",
    "plugin": "^0.3.3",
    "yaml": "^2.0.0-11",
    "yargs": "^17.4.0"
  }
}
```

tsconfig.json:
```
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "module": "es6",
    "target": "ES2020",
    "types": [
      "node",
      "jest"
    ],
    "typeRoots": [
      "./assets/js/types",
      "node_modules/@types"
    ],
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "lib": [
      "es2020",
      "dom",
      "dom.iterable"
    ],
    "experimentalDecorators": true,
    "outDir": "dist",
    "rootDir": "src",
    "declaration": true,
    "esModuleInterop": true
  },
  "moduleDirectories": [
    "node_modules",
    "assets"
  ],
  "exclude": ["./node_modules"]
}
```

**Comment by mrrzest** [comment]
Hi there @[jly36963](https://github.com/jly36963)! Would you be willing to sharing your expectations for when this bug will be reviewed? With libraries moving towards only supporting ESM, this issue makes using those modules difficult. Thank you.

**Comment by jly36963** [comment]
@mrrzest I can work on this one soon.

This project has a lot of features in cjs that haven't been implemented for esm and deno contexts. As people move away from node and/or cjs, more of these types of issues/requests are going to pop up. Pull requests are always welcome, as they will help speed up the process of filling in those missing functionalities

**Comment by justinmchase** [comment]
Basically, you should just not try to solve this. Just cut the feature. Make them create a `mod.ts` file which just exports all the other files in the directory then tell them to load `dir/mod.ts` instead. You won't be able to query for all the files in a directory, nor should you try to work around it.

**Comment by shadowspawn** [comment]
Support for `commandDir` in ESM files was added in Yargs 18.
