### ISSUE TITLE
[TypeScript ] `options.configuration` is undefined using ESM

### ISSUE THREAD

**Issue by raphtalia** [yargs/yargs#2221]
Running `ckts import test` or anything as a positional argument results in an error. I've found changing the builder in the command module to be synchronous fixes the issue. However documentation for the arguments and options then don't show up when ran with `--help`

**Versions**
yargs: 17.0.10
node: v18.0.0
ttypescript: 4.7.4

```
file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:311
                if (options.configuration['unknown-options-as-args'])
                                         ^

TypeError: Cannot read properties of undefined (reading 'unknown-options-as-args')
    at file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:311:42
    at Array.map (<anonymous>)
    at file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:310:32
    at Array.forEach (<anonymous>)
    at CommandInstance.postProcessPositionals (file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:309:36)
    at CommandInstance.populatePositionals (file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:260:14)
    at CommandInstance.applyMiddlewareAndGetResult (file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:234:34)
    at file:///C:/Users/kriss/Documents/GitHub/ckts/node_modules/yargs/build/lib/command.js:127:49

Node.js v18.0.0
```

**Entrypoint**
```ts
#!/usr/bin/env node --experimental-specifier-resolution=node

import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import cmdImport from "CLI/commands/import";

const y = yargs(hideBin(process.argv));

y.command(cmdImport).parseAsync();
```

**Command module**
```ts
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

const y = yargs(hideBin(process.argv));

export default {
  command: "import <path>",
  desc: "import Bethesda source files or archives",

  builder: async () =>
    y
      .positional("path", {
        type: "string",
        desc: "Path to the file or directory to import",
      })
      .option("interactive", {
        alias: "i",
        desc: "Interactive imports",
      }),

  handler: async ({ path }: { path?: string }) => {
    console.log(`Importing ${path}`);
  },
};
```

**tsconfig**
```json
{
  "compilerOptions": {
    "declaration": true,
    "module": "ESNext",
    "target": "ESNext",
    "lib": ["ESNext"],
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "removeComments": true,
    "composite": true,
    "outDir": "out",
    "baseUrl": "src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "paths": {
      "*": ["*"]
    },
    "plugins": [
      {
        "transform": "typescript-transform-paths",
        "exclude": ["**/node_modules/**"]
      },
      {
        "transform": "typescript-transform-paths",
        "exclude": ["**/node_modules/**"],
        "afterDeclarations": true
      }
    ]
  }
}
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
