### ISSUE TITLE
Issue with Czech locale

### ISSUE THREAD

**Issue by dreamscached** [yargs/yargs#2243]
Hi! I'm using yargs in my personal project and I seem to have issues with it when I run `./index.js --help`:

```
SyntaxError: syntax error in /home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/locales/cs.json
    at JSON.parse (<anonymous>)
    at Y18N._readLocaleFile (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/y18n/build/index.cjs:141:37)
    at Y18N.__ (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/y18n/build/index.cjs:30:18)
    at Object.P.n.help (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:16520)
    at Object.P.n.showHelp (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:20126)
    at Xt.showHelp (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:42577)
    at Xt.[runYargsParserAndExecuteCommands] (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:58654)
    at Xt.parse (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:40011)
    at Xt.parseSync (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/node_modules/yargs/build/index.cjs:1:40511)
    at Object.<anonymous> (/home/dreamscached/Dokumenty/Vývoj/Projekty/dreamscached/rexport/index.js:9:6)
```

**Comment by panther7** [comment]
Maybe add to "JSON validate" for prebuild/prerelease check.

**Comment by davidslaby** [comment]
The same issue

**Comment by bcoe** [comment]
Apologies for the bad release, and taking so long to land.
