### ISSUE TITLE
parseSync is not a function

### ISSUE THREAD

**Issue by faljse** [yargs/yargs#2344]
This typescript file throws Uncaught TypeError TypeError: (0 , yargs_1.default)(...).options(...).usage(...).parseSync is not a function
on execution.
Program compiles without errors.

```
import  yargs from 'yargs'

const argv = yargs(process.argv.slice(2))
.options({
    p: { type: 'number', demandOption: true },
    backend: { type: 'string', demandOption: true },
    user: { type: 'string', demandOption: true },
    sample: { type: 'number' },
    tools: { type: 'number'},
    log: { type: 'string'},
    d: { type: 'boolean'}
})
.usage('Usage: node_server -p [port] -backend [endpoint backend] -user [path/to/user.json] -sample [MinimumSamplingInterval in ms] -tools [Interval for checking tool nodes] -log [path/to/config_log.json] -d')
.parseSync();

export {argv};
```

```

Uncaught TypeError TypeError: (0 , yargs_1.default)(...).options(...).usage(...).parseSync is not a function
    at <anonymous> (c:\Users\martin\projects\opcuafrontend\build\argv.js:19:6)
    at Module._compile (internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (internal/modules/cjs/loader:1213:10)
    at Module.load (internal/modules/cjs/loader:1037:32)
    at Module._load (internal/modules/cjs/loader:878:12)
    at Module.require (internal/modules/cjs/loader:1061:19)
    at require (internal/modules/cjs/helpers:103:18)
    at <anonymous> (c:\Users\martin\projects\opcuafrontend\build\log.js:34:16)
    at Module._compile (internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (internal/modules/cjs/loader:1213:10)
    at Module.load (internal/modules/cjs/loader:1037:32)
    at Module._load (internal/modules/cjs/loader:878:12)
    at Module.require (internal/modules/cjs/loader:1061:19)
    at require (internal/modules/cjs/helpers:103:18)
    at <anonymous> (c:\Users\martin\projects\opcuafrontend\build\helper.js:31:15)
    at Module._compile (internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (internal/modules/cjs/loader:1213:10)
    at Module.load (internal/modules/cjs/loader:1037:32)
    at Module._load (internal/modules/cjs/loader:878:12)
    at Module.require (internal/modules/cjs/loader:1061:19)
    at require (internal/modules/cjs/helpers:103:18)
    at <anonymous> (c:\Users\martin\projects\opcuafrontend\build\ts_opcua_server.js:31:18)
    at Module._compile (internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (internal/modules/cjs/loader:1213:10)
    at Module.load (internal/modules/cjs/loader:1037:32)
    at Module._load (internal/modules/cjs/loader:878:12)
    at executeUserEntryPoint (internal/modules/run_main:81:12)
    at <anonymous> (internal/main/run_main_module:23:47)
```

**Comment by shadowspawn** [comment]
I was not able to reproduce with tsconfig created by `tsc --init`.

What version of yargs are you using? (`parseSync` got added in Yargs v17.)

If you are using 17 or higher, what is in your `tsconfig.json` file?

**Comment by faljse** [comment]
Oh.. there wasnt even a dependency on yargs..
Maybe it was using an older version from an indirect dependency

Works now; thx!

**Comment by shadowspawn** [comment]
Glad it is working for you now. Thanks for the update.
