### ISSUE TITLE
Use `node:` prefix for node imports.

### ISSUE THREAD

**Issue by lgarron** [yargs/yargs#2358]
When bundling a program that uses `yargs`, the bundler needs to know whether to include certain dependencies. In particular, `node` dependencies should be excluded.

Unfortunately, `yargs` does not currently use the `node:` prefix, which means:

- One has to enumerate these by hand (e.g. by running the build a few times and seeing which imports break).
- These imports are indistinguishable from `npm` packages with the same name (often polyfills that a coder may or may not want to include for separate reasons).

Many bundlers also support wildcards for ignores: for example, you can set `node:*` as [external packages](https://esbuild.github.io/api/#external) in `esbuild`.

So using a `node:` prefix for all imports of `node` modules would make it simpler and safer to produce correct bundled code when using `yargs`.

This is available for ESM back to node `12`, matching the compatibility defined here: https://github.com/yargs/yargs/blob/main/package.json#L125

**Comment by lgarron** [comment]
Looks like updating https://github.com/yargs/yargs/blob/e0823dd7e6ced7eaf1d7d1e67f77374f4ef5cbce/lib/platform-shims/esm.mjs is pretty trivial (and similar for CJS, although I don't need that myself), but the `yargs-parser` build breaks with:

```
npm ERR! [!] (plugin Typescript) Error: Debug Failure. Unhandled SyntaxKind: Unknown.
npm ERR! Error: Debug Failure. Unhandled SyntaxKind: Unknown.
npm ERR!     at pipelineEmitWithHintWorker (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:114185:22)
npm ERR!     at pipelineEmitWithHint (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113716:17)
npm ERR!     at pipelineEmitWithComments (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:117404:13)
npm ERR!     at pipelineEmit (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113656:13)
npm ERR!     at emitExpression (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113640:13)
npm ERR!     at emitExportAssignment (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:115652:13)
npm ERR!     at pipelineEmitWithHintWorker (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113929:32)
npm ERR!     at pipelineEmitWithHint (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113716:17)
npm ERR!     at pipelineEmitWithComments (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:117404:13)
npm ERR!     at pipelineEmit (/Users/lgarron/Code/git/github.com/yargs/yargs-parser/node_modules/typescript/lib/typescript.js:113656:13)
```

https://rollupjs.org/configuration-options/ includes `node:` prefixes in its very own examples, so clearly the Rollup project is aware of them and has a way to handle them, but I haven't figured out how.

**Comment by shadowspawn** [comment]
The error might be a dependency problem rather than `node:`. I saw similar error in yargs-parser (unrelated to `node:`):
- https://github.com/yargs/yargs-parser/issues/470
- https://github.com/yargs/yargs-parser/pull/478

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.

**Comment by lgarron** [comment]
> Feel free to open a new issue if it comes up again, with new information and renewed interest.

I'm not sure what new information there would be to provide. `yargs` uses `node:` prefixes for imports in some places now, but not throughout.


```
╭─── /home/codespace/test ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
├─ codespace@codespaces-9cfa56
│ npm install --save esbuild yargs
  echo 'import "yargs";' > test.ts
  npx -- esbuild --external:"node:*" --bundle test.ts
┴

up to date, audited 16 packages in 647ms

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✘ [ERROR] Could not resolve "assert"

    node_modules/yargs/lib/platform-shims/esm.mjs:3:44:
      3 │ import { notStrictEqual, strictEqual } from 'assert'
        ╵                                             ~~~~~~~~

  The package "assert" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "util"

    node_modules/yargs/lib/platform-shims/esm.mjs:6:24:
      6 │ import { inspect } from 'util'
        ╵                         ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "url"

    node_modules/yargs/lib/platform-shims/esm.mjs:7:30:
      7 │ import { fileURLToPath } from 'url';
        ╵                               ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/yargs/lib/platform-shims/esm.mjs:9:68:
      9 │ import { basename, dirname, extname, relative, resolve, join } from 'path'
        ╵                                                                     ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/escalade/sync/index.mjs:1:33:
      1 │ import { dirname, resolve } from 'path';
        ╵                                  ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs"

    node_modules/escalade/sync/index.mjs:2:38:
      2 │ import { readdirSync, statSync } from 'fs';
        ╵                                       ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "--platform=node" to do that, which will remove this error.

6 of 12 errors shown (disable the message limit with --log-limit=0)
┬                                                                                                                                               
├─ ⏱️ 1.456s 
├─ ❌ [1] command status
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I don't use `yargs` for my own projects anymore, so this would only be a concern for me if I'm bundling a third-party library/program that imports `yargs`.

**Comment by shadowspawn** [comment]
Thanks for the simple reproduction (and for the tidy original report).

I'm open to using the `node:` prefix, but this issue with no upvotes is not going to make it happen.

In this case "new information" might be it annoying someone else. 😁

**Comment by lgarron** [comment]
> I'm open to using the `node:` prefix, but this issue with no upvotes is not going to make it happen.

Well, I'd be happy to send a PR. The main issue with that is that a responsible PR would add something robust to avoid a regression, and this repo uses `eslint` (which doesn't have a rule like Biome's [`useNodejsImportProtocol`](https://biomejs.dev/linter/rules/use-nodejs-import-protocol/)). All other options I can think of are either slow (using `tsc`) or require a new dependency (e.g. Biome or `esbuild`).

**Comment by shadowspawn** [comment]
> Well, I'd be happy to send a PR. 

Your example shows some imports in the `escalade` dependency.  I am not clear whether would also need to update more of yargs family to get full benefits: `yargs-parser`, `cliui`, and `y18n`.

In fact `esbuild` appears to have built-in support for this, which seems a good match for the problem?

> You can use "--platform=node" to do that, which will remove this error.

**Comment by lgarron** [comment]
> In fact `esbuild` appears to have built-in support for this, which seems a good match for the problem?
> 
> > You can use "--platform=node" to do that, which will remove this error.

This is useful if you're the one invoking the final application build, but it's not as useful for library authors. We have to ship code taking into account all bundlers and runtimes, for which unprefixed imports are semantically ambiguous but prefixed ones are not.

Anyhow, since I don't use `yargs` myself anymore and don't expect I ever will again if I can avoid it, I think I'll just leave this alone.
