### ISSUE TITLE
[bug]: unexpected "--help" command execution when throw error in command handler

### ISSUE THREAD

**Issue by OceanPresentChao** [yargs/yargs#2368]
# Description
when we use .command(cmd, desc, [builder], [handler]) method, if the async handler function we pass in throws an error, it will result in an unexpected "--help" command execution.
# Enviornment
- Binaries:
    Node: 16.18.0 - /usr/local/share/nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - /usr/local/share/nvm/versions/node/v16.18.0/bin/npm
- npmPackages:
    yargs:  ^17.7.2
# Reproduction
``` javascript
// index.js
import yargs from "yargs";
async function runCLI(){
  const program = yargs()
// handler function must be async!!!
  program.command(["build", "$0", "bundle", "b"], "run the build",()=>{},async()=>{
      throw new Error("HELLO")
  })
  program.parseAsync(process.argv)
}

runCLI()

```
if we run command:
```javascript
node index.js build
```
it will output, we can see it execute "--help" command once unexpectedly
```javascript
run the build

Options:
  --help     Show help                                            [boolean]
  --version  Show version number                                  [boolean]

Error: HELLO
    at Object.handler (index.js:5:13)
    at pnpm/yargs@17.7.2/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (pnpm/yargs@17.7.2/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/command.js:128:20)
    at YargsInstance.[runYargsParserAndExecuteCommands] (.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/yargs-factory.js:1412:93)
    at YargsInstance.parse (pnpm/yargs@17.7.2/node_modules/yargs/build/lib/yargs-factory.js:707:63)
    at YargsInstance.parseAsync (.pnpm/yargs@17.7.2/node_modules/yargs/build/lib/yargs-factory.js:737:35)
    at runCLI (index.js:7:11)
```

**Comment by OceanPresentChao** [comment]
Oh sorry, I noticed that yargs has an option `showHelpOnFail`, we can set it to false and the problem will be done.
But, if the handler function is not async, it will not show help info even though we do not specify showHelpOnFail as false.
