### ISSUE TITLE
yargs 4.1 sub-commands using builder do not work

### ISSUE THREAD

**Issue by gajus** [yargs/yargs#400]
``` js
#!/usr/bin/env node

import yargs from 'yargs';

yargs
    .command('update', (subYargs) => {
        return subYargs
            .options({
                exclude: {
                    default: [],
                    describe: 'A space-separated list of dependencies not to include in the bundledDependencies definition.',
                    type: 'array'
                }
            });
    }, (argv) => {
        console.log(argv.exclude);
    })
    .argv;

```

Command:

``` sh
node ./dist/bin/index.js update --exclude a b c
```

Output:

```
undefined
```

**Comment by gajus** [comment]
It looks like modifying the builder definition has not effect whatsoever:

```
#!/usr/bin/env node

import yargs from 'yargs';

yargs
    .command('update', (subYargs) => {
        return subYargs
            .usage('test')
            .help()
            .options({
                exclude: {
                    default: [],
                    describe: 'A space-separated list of dependencies not to include in the bundledDependencies definition.',
                    type: 'array'
                }
            });
    }, (argv) => {
        console.log(argv.exclude);
    })
    .argv;
```

Command:

```js
node ./dist/bin/index.js update --help
```

Output:

```
undefined
```

**Comment by nexdrew** [comment]
@gajus I think you need a 2nd argument that is either a string (short description of the command) or the value `false` (if the command should be "hidden" from help text).

So try this instead:

```js
    .command('update', 'Update dependencies', (subYargs) => {
        return subYargs
            .options({
                exclude: {
                    default: [],
                    describe: 'A space-separated list of dependencies not to include in the bundledDependencies definition.',
                    type: 'array'
                }
            });
    }, (argv) => {
        console.log(argv.exclude);
    })
```

Unfortunately the description argument for the [`.command()` method](http://yargs.js.org/docs/#methods-commandcmd-desc-builder-handler) is required.

**Comment by bcoe** [comment]
@nexdrew @gajus perhaps we should make this a bit smarter, if it sees a function or object for the second argument default to a blank description., and assume that it's been passed a builder.

**Comment by gajus** [comment]
I think you are just missing simple type assertions. I think it is a valid requirement to have command description. But it should not fail silently when unexpected type is provided.

**Comment by bcoe** [comment]
🎉 we added type assertions quite some time ago, to help folks catch errors like this earlier on:

```bash
YError: Invalid second argument. Expected string or boolean but received function.
    at argumentTypeError (/Users/benjamincoe/bcoe/yargs/lib/argsert.js:67:9)
    at /Users/benjamincoe/bcoe/yargs/lib/argsert.js:49:39
    at Array.forEach (<anonymous>)
```
