### ISSUE TITLE
.command(module) does not work with a Babel ES6 class using static props and methods

### ISSUE THREAD

**Issue by vjpr** [yargs/yargs#509]
I want to be able to do this:

```js
import shipmate from '../index'

export default class {

  static command = 'publish';

  static describe = 'Run checks and publish to npm';

  static builder(yargs) {

  }

  static handler(argv) {
  
  }

}

```

The error message at the moment is:

```js
TypeError: cmd.split is not a function
    at parseCommand (/Users/Vaughan/dev-live/shipmate/node_modules/yargs/lib/command.js:48:28)
    at Object.self.addHandler (/Users/Vaughan/dev-live/shipmate/node_modules/yargs/lib/command.js:28:25)
    at Object.Yargs.self.command (/Users/Vaughan/dev-live/shipmate/node_modules/yargs/yargs.js:204:13)
```

`typeof cmd === 'object'` in the following check, prevents using an ES6 class with static methods.

*lib/command.js*
```
    if (typeof cmd === 'object' && typeof cmd.command === 'string' && cmd.builder && typeof cmd.handler === 'function') {
      self.addHandler(cmd.command, extractDesc(cmd), cmd.builder, cmd.handler)
      return
    }
```

**Workaround**

Pass a class instance to yargs instead.

```js
import Publish from './publish'

  const yargs = yargsModule
    .usage('Usage: $0')
    .command(new Publish)
```

**Comment by shlomisas** [comment]
When i have this such command file:

```javascript
export default {
    command: 'xxx',
    describe: 'Run xxx',
    builder: {
        id: {
            alias: 'i',
            demand: true
        }
    }
};
```

 it also gives me `TypeError: cmd.split is not a function`

Any idea why?

**Comment by nexdrew** [comment]
@shlomisas I think it expects a `handler` function to be defined for modules. We are trying to be more lenient with requirements for command modules (see #492) and we made some changes in 4.8.0 (`yargs@next`) towards fixing this, but there's still a little work left.

**Comment by shlomisas** [comment]
Yes, looks like this is the only way to run it now with the API of:

`.command(module)`

This is my new working code:

```javascript
static getCommandModule(){
	return {
		command: `xxx <id>`,
		describe: 'Run a xxx task',
		builder: {},
		handler: function (argv) {}
	}
}
```
