### ISSUE TITLE
'Cannot read property '_' of undefined' for command handlers

### ISSUE THREAD

**Issue by addisonj** [yargs/yargs#565]
Here is a pretty minimal reproduce:

```JavaScript
let yargs = require('yargs')
let cli = yargs
.usage('Usage: $0 <command> [args...]')
.command('submit <file>', 'submit the file', (yargs) => yargs.argv, function(argv) {
  console.log('submit')

})
.command('start', 'start the thing', (yargs) => yargs.argv, function(argv) {
  console.log('start')
})
console.log(cli.argv)
```

This results in `Cannot read property '_' of undefined`

if I throw in a bit of debugging in the try catch, I get this stack:

```
TypeError: Cannot read property '_' of undefined
    at populatePositional (/Users/ahigham/Projects/ftl-engine/node_modules/yargs/lib/command.js:120:18)
    at Object.self.runCommand (/Users/ahigham/Projects/ftl-engine/node_modules/yargs/lib/command.js:110:5)
    at parseArgs (/Users/ahigham/Projects/ftl-engine/node_modules/yargs/yargs.js:648:24)
    at Object.Yargs.Object.defineProperty.get [as argv] (/Users/ahigham/Projects/ftl-engine/node_modules/yargs/yargs.js:609:16)
    at Object.<anonymous> (/Users/ahigham/Projects/ftl-engine/cli.js:12:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I tried both 4.7.x and 4.8.x releases... both were broken

**Comment by nexdrew** [comment]
@addisonj Try replacing your builder `(yargs) => yargs.argv` with `(yargs) => yargs` or just `{}`.

The API does not currently expect the builder to parse and return argv itself.

**Comment by addisonj** [comment]
well now I feel silly, apparently I was looking at some older example that got me thinking the API was different than it is.... sorry for the trouble and thanks for the tip :)

**Comment by nexdrew** [comment]
@addisonj No worries, some of our docs may be out of date. Feel free to open issues for any other odd things you run into, and thanks for using yargs!
