### ISSUE TITLE
commandDir cannot work with es6 module export keyword

### ISSUE THREAD

**Issue by ghost** [yargs/yargs#571]
i use commandDir to import my es6 subcommand files, but it does not work, anyone know the solution?

**Comment by maxrimue** [comment]
Could you please provide us the actual code that is causing problems? Thanks!

**Comment by bcoe** [comment]
@callmelanmao as @maxrimue requests, mind providing some sample code 👍

**Comment by callmelanmao** [comment]
@bcoe  @maxrimue 

sorry for being late, 

error code 
```
$ ant test
D:\code\ant\ant\Worker.js:9
export default Worker;
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\code\ant\ant\test.js:3:16)
    at Module._compile (module.js:541:32)
```

source code

test.js
```
'use strict';

const Worker = require('./Worker.js');

exports.command = 'test <name>';

exports.desc = 'test for commandDir';

exports.builder = function (yargs) {
  return yargs
    .help('h');
}

exports.handler = function (argv) {
  new Task(argv.name, argv.o, argv.s).start();
}
```

Worker.js in the same dir with test.js
```
function Worker(name) {
  this.name = name;
}

Worker.prototype.test = function() {
  console.log(this.name);
}
export default Worker;
```

my top command line name is ant, and this `test.js` is just for test,  it's not the original code the error occurred  to me before

**the title of this issue may not correct, yargs cannot load the es6 module, and nothing is wrong with `commandDir` iterface**

thanks for help~

**Comment by bcoe** [comment]
@callmelanmao what are you using to manage your ES6 code, e.g., are you running it through a babel compiler?

The syntax for `export default Worker;` is not yet supported by the JavaScript language, so I think you'll need to add a build step using:

https://babeljs.io/

before you're able to use the code above 👍

**Comment by maxrimue** [comment]
@callmelanmao as @bcoe pointed out, the `export` keyword is part of ES6, and right now is not natively supported in any browser or Node.js, but eventually will be. You can read more about it [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/export). In the meantime, you can use a tool like [babel](https://babeljs.io), which will let you write `export`, but it will use another currently supported way to do this behind the scenes. Alternatively, you can use `module.exports`.

**Comment by SimonSchick** [comment]
@bcoe Would you be willing to re-visit this? With TypeScript and native modules on the horizon I think supporting a specific export such as `handler` or simply `default` would be beneficial.

**Comment by rulatir** [comment]
This is relevant again, please reopen.

**Comment by mleguen** [comment]
Now that we dropped support for node 6, we should indeed add support for loading es6 command module.

**Comment by mleguen** [comment]
Yargs depends on `require-directory` for this, which does not look esm compatible. We would have to look for another module which does.

**Comment by mleguen** [comment]
This would also mean we would have to deal with asynchronously loaded command modules (dynamic import of esm modules is asynchronous) in yargs which is not...

**Comment by rulatir** [comment]
Looping over files in a directory is not hard to write on the application side, so I'd say this is way less urgent than e.g. #1098.

**Comment by fabis94** [comment]
This is a pretty important feature, ES6 modules are pretty much standard now. Here's a workaround for anyone who found this thread:

```
    .commandDir("commands", {
      visit(commandModule) {
        return commandModule.default;
      },
    })
```

Basically, I'm using the `visit` option of the `commandDir` method to take the module as encountered by yargs and return its default export.

**Comment by mustermeiszer** [comment]
> This is a pretty important feature, ES6 modules are pretty much standard now, so I hope this gets fixed soon. Here's a workaround for anyone who found this thread:
> 
> ```
>     .commandDir("commands", {
>       visit(commandModule) {
>         return commandModule.default;
>       },
>     })
> ```
> 
> Basically, I'm using the `visit` option of the `commandDir` method to take the module as encountered by yargs and return its default export.

I am unable to create a solution with this advice. Which is probably because of my novice knowledge about javascript. 
Would appreciate help a lot. 

I have two subcommands I want to refer to. The modules both are exporting `command`, `describe`, `builder`, and `handler` as their default.  But I am unable to find out, how I am using the visit command properly. Especially what must `commandModule`be (path to module, but is it then even possibly to return two modules?)?

Thanks in advance for your help!

**Comment by fabis94** [comment]
`commandModule` is going to be the exports object from the imported module. So the default export is going to be available at `commandModule.default`, named export `foo` is going to be available at `commandModule.foo` etc.

The visit function should return the `CommandModule` object, so the object that has command, describe, builder etc. props.

If your visit function uses the default export then your command module file should look like this:
```javascript
const module = {
  command: 'x',
  handler() {
   return 1;
 }
};
export default module;
```

**Comment by eden-lane** [comment]
@fabis94 I'm still getting this error.
My code:
```ts
// src/commands/generate.ts
const module = {
  command: 'generate',
  describe: 'generate something',
  aliases: ['g'],

  builder: function () {
    // return yargs.commandDir('generate')
  },

  handler: function () {}
}


export default module;

```

```ts
// src/cli.ts
import yargs from 'yargs';

yargs(process.argv.slice(2))
  .commandDir('commands', {
    visit(commandModule) {
      return commandModule.default;
    }
  })
  .demandCommand()
  .help()
  .argv;

```

**Comment by kvz** [comment]
@eden-lane I also had to add this


```js
extensions: process.env.NODE_ENV === 'development' ? ['js', 'ts'] : ['js'],
```

perhaps it works for you?

**Comment by manchuck** [comment]
Another workaround is to directly import the directory where all the commands then loop over the module add them using the `command` API:

commands/index.js:
```js
export {default as commandOne} from "./commandOne.js";
export {default as commandTwo} from "./commandTwo.js";
```

commands/commandOne.js
```js
const module = {
    command: "one",
    handler: function() {
        console.log("I am command one");
    },
};

export default module;
```

commands/commandTwo.js
```js
const module = {
    command: "two",
    handler: function() {
        console.log("I am command two");
    },
};

export default module;
```

run.js
```js
import * as commands from "./commands/index.js";
import _ from "lodash";
import yargs from "yargs";

// eslint-disable-next-line new-cap
const cli = yargs(process.argv.slice(2))
    .demandCommand()
    .help();

_.map(
    commands,
    (command) => {
        cli.command(command);
    },
);

cli.argv;
```

**Comment by shadowspawn** [comment]
Support for `commandDir` in ESM files was added in Yargs 18.
