### ISSUE TITLE
help with one more breaking change I missed...

### ISSUE THREAD

**Issue by osher** [yargs/yargs#629]
`yargs.help()` used to give me the help text.
I noted that it changed in v3, and now it enables some auto-help option, which I'm not interested in, because I need to append descriptive `epilog`s by my own logic.

I try to get the help text according to the new API as I understand it, but get this:

```
yargs = require('yargs')
  .usage('foo').demand(['x'])
  .options({ f: { alias: 'foo' }, b : { alias: 'bar' } })

console.log( yargs.getUsageInstance().help() )
```

which throws:
```
TypeError: Cannot convert undefined or null to object
    at Object.self.help (C:\ws\lesson14\node_modules\yargs\lib\usage.js:154:22)
    at repl:3:22
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:504:10)
    at emitOne (events.js:101:20)
```

reproduced on versions `5.x`, `4.x` and `3.x`...  - so it's probably me...

Any point in the right direction?

**Comment by osher** [comment]
Ai ai ai.. I now remember...

I can use `showHelp()` and give it an injected handler ....
