### ISSUE TITLE
handlers still get called even after check() throws an error

### ISSUE THREAD

**Issue by stevenxxiu** [yargs/yargs#711]
The command handler still gets called even after check() throws an error:

    .command('add [num]', 'add num', (yargs) => yargs.default('num', 1).check((argv) => {throw new Error()}), (argv) => {console.log('test')})

**Comment by maxrimue** [comment]
For some reason I can't reproduce this bug. Running your code gets me this output:
```shell

handlerCheck.js add [num]

Optionen:
  --num                                                            [Standard: 1]

Error
    at yargs.default.check (/Users/maxr/dev/test/yargs/handlerCheck.js:15:108)
    at Object.self.customChecks (/Users/maxr/dev/test/yargs/node_modules/yargs/lib/validation.js:205:18)
    at parseArgs (/Users/maxr/dev/test/yargs/node_modules/yargs/yargs.js:997:20)
    at Object.get [as argv] (/Users/maxr/dev/test/yargs/node_modules/yargs/yargs.js:860:16)
    at Object.self.runCommand (/Users/maxr/dev/test/yargs/node_modules/yargs/lib/command.js:153:42)
    at parseArgs (/Users/maxr/dev/test/yargs/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/Users/maxr/dev/test/yargs/node_modules/yargs/yargs.js:860:16)
    at Object.<anonymous> (/Users/maxr/dev/test/yargs/handlerCheck.js:15:155)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Could you provide us with the OS and yargs version you're using? Thanks for creating the issue!

**Comment by bcoe** [comment]
I can no longer reproduce this issue in the latest version of yargs. Thanks for the error report 😄
