### ISSUE TITLE
Exception being thrown when using nargs

### ISSUE THREAD

**Issue by jim-coffey** [yargs/yargs#759]
yargs ^6.6.0

Code
```
  const argv = yargs.usage(CONSTANTS.COMMAND_USAGE)
                    .example(CONSTANTS.COMMAND_EXAMPLE)
                    .option('f', {
                      alias: 'file',
                      describe: 'Comma separated list of file extensions'
                    })
                    .nargs('f', 1)
                    .parse(args);
```

When failing to pass an argument for `-f`, then an exception is being thrown - rather than nice message about usage : 
```
/node_modules/yargs/yargs.js:988
      if (parsed.error) throw parsed.error
                        ^

Error: Not enough arguments following: f
    at Error (native)
    at eatNargs (node_modules/yargs/node_modules/yargs-parser/index.js:301:48)
    at parse (node_modules/yargs/node_modules/yargs-parser/index.js:246:15)
    at Function.Parser.detailed (node_modules/yargs/node_modules/yargs-parser/index.js:756:10)
    at parseArgs (node_modules/yargs/yargs.js:873:27)
    at Object.Yargs.self.parse (node_modules/yargs/yargs.js:499:18)
    at module.exports.args (lib/utils/parseOptions.js:67:22)
    at Object.<anonymous> (finder.js:17:23)
    at Module._compile (module.js:409:26)
    at loader (node_modules/babel-register/lib/node.js:144:5)
```

Perhaps an issue when used with the `.parse()` method?

**Comment by bcoe** [comment]
@jim-coffey thanks for the bug report, definitely seems like something is slipping through the cracks 👍

**Comment by bcoe** [comment]
@jim-coffey running this testing code:

```js
const argv = require('./').usage('usage')
                  .example('example')
                  .option('f', {
                    alias: 'file',
                    describe: 'Comma separated list of file extensions'
                  })
                  .nargs('f', 1)
                  .parse(['-f']);
```

my output is:

```bash
usage

Options:
  -f, --file  Comma separated list of file extensions

Examples:
  example

Not enough arguments following: f
```

I think, _perhaps_, this issue has been addressed in some of the refactoring we've done in recent months. Could you confirm?

**Comment by mleguen** [comment]
I can confirm this issue is closed.
