### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by GongT** [yargs/yargs#761]
```
TypeError: Cannot read property 'options' of undefined
    at unfreeze (/data/test/node_modules/yargs/yargs.js:156:21)
    at Object.Yargs.self.parse (/data/test/node_modules/yargs/yargs.js:501:5)
    at Object.<anonymous> (/data/test/src/index.ts:153:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

/data/test/src/index.ts:153 is `  .parse(process.argv.slice(2))`

but if I change it to `   .argv`, everything works.

what's the different about these two method??

**Comment by bcoe** [comment]
@GongT could you please provide an example application that is causing this exception? it should be impossible to bump into the state that you're seeing.
