### ISSUE TITLE
yargs.choices() with 0 arguments is valid usage but produces a YError

### ISSUE THREAD

**Issue by FallingSnow** [yargs/yargs#925]
I'm unsure of whether this is intended behavior but running the following code

```js
const yargAliases = yargs.choices().parsed.aliases;
console.log(yargAliases);
```

results in

```js
YError: Not enough arguments provided. Expected 1 but received 0.
    at module.exports (/home/ayrton/Documents/nmmes-cli/node_modules/yargs/lib/argsert.js:25:13)
    at Object.Yargs.self.choices (/home/ayrton/Documents/nmmes-cli/node_modules/yargs/yargs.js:238:5)
    at Object.<anonymous> (/home/ayrton/Documents/nmmes-cli/src/options.js:229:27)
    at __webpack_require__ (/tmp/nmmes-cli/webpack/bootstrap 5b73a9e9a66d414b9dd2:19:1)
    at Object.<anonymous> (/tmp/nmmes-cli/nmmes-cli.js:261:70)
    at __webpack_require__ (/tmp/nmmes-cli/webpack/bootstrap 5b73a9e9a66d414b9dd2:19:1)
    at Object.<anonymous> (/tmp/nmmes-cli/nmmes-cli.js:1418:18)
    at __webpack_require__ (/tmp/nmmes-cli/webpack/bootstrap 5b73a9e9a66d414b9dd2:19:1)
    at /tmp/nmmes-cli/webpack/bootstrap 5b73a9e9a66d414b9dd2:65:1
    at /tmp/nmmes-cli/nmmes-cli.js:82:10
    at webpackUniversalModuleDefinition (/tmp/nmmes-cli/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/tmp/nmmes-cli/webpack/universalModuleDefinition:10:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
{ version: [],
  help: [],
  g: [ 'temp-directory', 'tempDirectory' ],
  'temp-directory': [ 'g', 'tempDirectory' ],
  tempDirectory: [ 'g', 'temp-directory' ],
  d: [ 'destination' ],
  destination: [ 'd' ],
  v: [ 'verbose' ],
  verbose: [ 'v' ],
  skip: [],
  p: [ 'preview' ],
  preview: [ 'p' ],
  'log-file': [ 'logFile' ],
  logFile: [ 'log-file' ],
  m: [ 'preset' ],
  preset: [ 'm' ],
  n: [ 'native-language', 'nativeLanguage' ],
  'native-language': [ 'n', 'nativeLanguage' ],
  nativeLanguage: [ 'n', 'native-language' ],
  f: [ 'output-format', 'outputFormat' ],
  'output-format': [ 'f', 'outputFormat' ],
  outputFormat: [ 'f', 'output-format' ],
  c: [ 'video-codec', 'videoCodec' ],
  'video-codec': [ 'c', 'videoCodec' ],
  videoCodec: [ 'c', 'video-codec' ],
  profile: [],
  q: [ 'quality' ],
  quality: [ 'q' ],
  'he-audio': [ 'heAudio' ],
  heAudio: [ 'he-audio' ],
  'force-he-audio': [ 'forceHeAudio' ],
  forceHeAudio: [ 'force-he-audio' ],
  'downmix-he-audio': [ 'downmixHeAudio' ],
  downmixHeAudio: [ 'downmix-he-audio' ],
  bitdepth: [],
  screenshots: [],
  'normalize-level': [ 'normalizeLevel' ],
  normalizeLevel: [ 'normalize-level' ],
  scale: [],
  stats: [],
  debug: [],
  delete: [],
  l: [ 'preview-length', 'previewLength' ],
  'preview-length': [ 'l', 'previewLength' ],
  previewLength: [ 'l', 'preview-length' ],
  simple: [],
  test: [] }
```

**Comment by ev1stensberg** [comment]
Same over at `webpack-cli`

**Comment by bcoe** [comment]
@ev1stensberg what's the specific code that's giving you an issue? a few months ago we introduced a library which validates the arguments parsed to yargs' core API, my guess is we're being too strict in a specific edge-case.

CC: @FallingSnow sorry for dropping this on the floor for so long.

**Comment by bcoe** [comment]
This is working as intended (_choices expects at least one argument._)
