### ISSUE TITLE
Error Handler not working with `commandDir` ?

### ISSUE THREAD

**Issue by digitalkaoz** [yargs/yargs#953]
Hey,

i have a simple setup:

```js
//index.js

yargs
    .commandDir(`${__dirname}/commands`)
    .argv
```

```js
//commands/foo.js

module.exports = {
    command: "foo",
    desc: "some desc",
    builder: (yargs) => {
        return yargs
            .exitProcess(false)
            .fail((...args) => {
                console.log("handle error");
                process.exit(1);
            });
    },
    handler: () => {
        throw new Error("test");
    }
};
```

```bash
$ node index.js foo

node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: test
    at Object.handler (commands/foo.js:13:15)
    at Object.self.runCommand (node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (node_modules/yargs/yargs.js:927:19)
   ...
```

it never reaches the `fail` function?! what am i doing wrong here?

i simply want to exit with errorCode `1` without displaying the original Error but instead a custom error message.

**Comment by bcoe** [comment]
@digitalkaoz going to reply in your pull-request 👍

**Comment by bcoe** [comment]
let's start a discussion in #1102 about how to better handle asynchronous commands.
